# Generated by Django 3.0.8 on 2020-08-27 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0002_userprofile_default_shipping_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='default_shipping_name',
        ),
    ]
